### ISSUE TITLE
Be able to switch Techdocs local/external mode with configuration

### ISSUE THREAD

**Issue by christophe-f** [janus-idp/backstage-showcase#160]
### What do you want to improve?

It would be great to be able to use the same Janus Showcase image and run Techdocs locally or with an external storage. This will be easier to use for demo, but can still scale if used in production.

### What is the current behavior?

Current the image is using the external storage only.

```
techdocs:
  builder: 'external'
  generator:
    runIn: 'local'
  publisher:
    type: 'awsS3'
```

### What is the new behavior?

Externalize the config to be able to switch local or external with:

```
techdocs:
  builder: ${TECHDOCS_BUILDER_TYPE}
  generator:
    runIn: ${TECHDOCS_GENERATOR_TYPE}
  publisher:
    type: ${TECHDOCS_PUBLISHER_TYPE}
```

### :warning: Is this a breaking change?

_Put an `x` in the boxes that apply_

- [ ] Yes
- [x] No
- [ ] Don't know
