### ISSUE TITLE
Customize the branding for Janus like logos, primary color etc

### ISSUE THREAD

**Issue by invincibleJai** [janus-idp/backstage-showcase#540]
**Goal**
As a user, I would like the ability to customize the branding for Janus. Something like the below can be provided in `app-config.yaml`

```
app:
  branding:
    fullLogo: ${BASE64_SVG_FULL_LOGO_URL}
    iconLogo: ${BASE64_SVG_ICON_LOGO_URL}
    theme:
      primaryColor: ${PRIMARY_COLOR}
```

in case of multiple supported themes i.e in case of light and dark can be something like below

```
 app:
  branding:
    fullLogo: ${BASE64_SVG_FULL_LOGO_URL}
    iconLogo: ${BASE64_SVG_ICON_LOGO_URL}
    theme:
      - light:
          primaryColor: ${PRIMARY_LIGHT_COLOR}
     - dark:
          primaryColor: ${PRIMARY_DARK_COLOR}
```

ThemeProvider should be able to read values from config and react to that.
