### ISSUE TITLE
Make header color configurable

### ISSUE THREAD

**Issue by Zaperex** [janus-idp/backstage-showcase#556]
### What do you want to improve?
Add configurations for the header in the showcase
![image](https://github.com/janus-idp/backstage-showcase/assets/50030060/a9093ae6-339e-4d87-bd48-c5badebba624)

### What is the current behavior?
Currently the header is stuck with the janus theme and cannot be configured

### What is the new behavior?
Add a configuration in the `app-config.yaml` to allow user to configure the header theme.
```yaml
app:
  branding:
    theme:
      - header:
          color1: ${HEADER_COLOR_1}
          color2: ${HEADER_COLOR_2}
```
