### ISSUE TITLE
Test the showcase with AD MFA.

### ISSUE THREAD

**Issue by christophe-f** [janus-idp/backstage-showcase#614]

**Comment by Zaperex** [comment]
@christophe-f just want to confirm, but is AD supposed to stand for Active Directory or Azure DevOps?

**Comment by christophe-f** [comment]
Azure Directory

**Comment by Zaperex** [comment]
@christophe-f so it appears the Azure Active Directory is now know as Microsoft Entra ID. Backstage currently has the Azure EasyAuth provider that authenticates users using Microsoft Entra ID (formerly Azure Active Directory) for PaaS service hosted in Azure that support Easy Auth, such as Azure App Services. I was wondering if this issue overlaps with this [Jira issue involving testing Azure EasyAuth Provider](https://issues.redhat.com/browse/RHIDP-580)?

**Comment by Zaperex** [comment]
Update: Authenticating using the azure auth provider for Azure Active Directory (now called Microsoft Entra ID) with Multi-Factor Authentication works.

I used the 30 day Microsoft Entra ID P2 free trial to setup a test organization on Azure for Microsoft Entra ID. I setup an app with the permissions described in the backstage docs for the [azure auth provider](https://backstage.io/docs/auth/microsoft/provider/#configure-app-registration-on-azure), and adding the proper web direct URL.

Then I setup a test user for the organization and enforced MFA for the user. Then I logged in with the test user in an incognito tab to setup the 2FA app.

Then I applied the configurations for the auth provider:
```yaml
auth:
  environment: production
    microsoft: 
      production: 
        clientId: ${AZURE_CLIENT_ID}
        clientSecret: ${AZURE_CLIENT_SECRET}
        tenantId: ${AZURE_TENANT_ID}
signInPage: microsoft
```
When I sign-in, I get redirected to sign-in using an azure account and when I do, it asks for password and MFA. Once MFA is complete, the user is then able to login.
