### ISSUE TITLE
Allow including files and overriding their content in the list of dynamic plugins 

### ISSUE THREAD

**Issue by davidfestal** [janus-idp/backstage-showcase#641]
We should enhance the list of dynamic plugins to install (used in the helm chart and config map) in order to allow file inclusion and overriding., and enabling/disabling of plugins.

Instead of having simply a YAML list like this:

``` yaml
- package: ./dynamic-plugins/dist/roadiehq-scaffolder-backend-module-utils-dynamic
  pluginConfig:
    someConfig: {}

- package: anotherOne

...
```

We would have both a list of plugins and a list of includes (files):

``` yaml
includes:
  - 'dynamic-plugins.default.yaml'
  
plugins:
  - package: ./dynamic-plugins/dist/roadiehq-scaffolder-backend-module-utils-dynamic
    pluginConfig:
      someConfig: {}
      
  - package: disabledOne
    disable: true
```

In addition to that, as shown just above, we would add an optional `disable` (`false` by default`) to the list of plugins.

Default value for includes would be: `[ 'dynamic-plugins.default.yaml' ]`
So this included file (present in the container image) would contain, with the same syntax, the `plugins` list filled with all the plugins available in the SHowcase container image, either enabled or disabled by default.

The list of plugins in `plugins` would possibly override the plugins imported by included files.

So you could for example:
- remove all the plugins enabled by default by simply using: includes: []
- add other includes (coming from some additional file brought by other means ... or by some UI in the future
- override an element of what has been brought through includes, by adding it in the list again with the changed values like `pluginConfig` or `disabled`
