### ISSUE TITLE
Exposed Github App Private Key in Backstage Logs

### ISSUE THREAD

**Issue by Zaperex** [janus-idp/backstage-showcase#713]
### Describe the bug
When deploying the showcase with the helm chart, the logs will expose a github app private key in the [UrlReader section of the log](https://github.com/janus-idp/backstage-showcase/blob/58ed7c0cc919cefe9cf6e2ac854f6dc92b795de7/packages/backend/src/index.ts#L63). 

```bash
2023-11-03T14:29:55.791Z backstage info Created UrlReader {"readers":[{"reader":{"integration":{"integrationConfig":{"host":"dev.azure.com"}},"deps":{"treeResponseFactory":{"workDir":"/tmp"},"credentialsProvider":{"providers":{}}}}},{"reader":{"integration":{"integrationConfig":{"host":"bitbucket.org","apiBaseUrl":"https://api.bitbucket.org/2.0"}},"deps":{"treeResponseFactory":{"workDir":"/tmp"}}}},{"reader":{"integration":{"integrationConfig":{"host":"bitbucket.com","apiBaseUrl":"[REDACTED]","username":"[REDACTED]","password":"[REDACTED]"}},"deps":{"treeResponseFactory":{"workDir":"/tmp"}}}},{"reader":{"integration":{"integrationConfig":{"host":"github.com","apiBaseUrl":"https://api.github.com/","rawBaseUrl":"https://raw.githubusercontent.com/","apps":[{"appId":371748,"clientId":"Iv1.93aaea6de25920a7","clientSecret":"[REDACTED]","webhookSecret":"[REDACTED]","privateKey":"-----BEGIN RSA PRIVATE KEY-----\nMY_EXPOSED_PRIVATE_KEY\n-----END RSA PRIVATE KEY-----\n"}]}},"deps":{"treeResponseFactory":{"workDir":"/tmp"},"credentialsProvider":{"providers":{}}}}},{"reader":{"integration":{"integrationConfig":{"host":"gitlab.com","token":"[REDACTED]","apiBaseUrl":"https://gitlab.com/api/v4","baseUrl":"https://gitlab.com/"}},"deps":{"treeResponseFactory":{"workDir":"/tmp"}}}},{"reader":{"credsManager":{"accountCredentialProviders":{},"accountDefaults":{},"mainAccountCredentialProvider":{}},"integration":{"integrationConfig":{"host":"amazonaws.com"}},"deps":{"treeResponseFactory":{"workDir":"/tmp"}}}},{"reader":{}}]}
```
### Expected Behavior
The private key should be redacted: `"privateKey":"[REDACTED]\n"`
### What are the steps to reproduce this bug?

1. Add the [v2.8.1 janus-idp helm chart](https://github.com/janus-idp/helm-backstage/tree/31cb6863b793da7893b46420e2beb2f90a5426fe) with `helm repo add janus-idp https://janus-idp.github.io/helm-backstage`
2. Export the helm chart values into a file with `helm show values janus-idp/backstage > values.yaml`
3. Set image for the backstage instance to be `quay.io/janus-idp/backstage-showcase/next-ff2e29c` in the `values.yaml`
4. Create ConfigMap containing the following configurations:
   <details><summary>Janus Showcase ConfigMap</summary>
    
    ```yaml
    kind: ConfigMap
    apiVersion: v1
    metadata:
      name: app-config-showcase
      namespace: <deployed-namespace>
    data:
      app-config-showcase.yaml: |
        integrations:
          # Plugin: GitHub
          github:
            - host: github.com
              apps:
                - appId: ${GITHUB_APP_APP_ID}
                  clientId: ${GITHUB_APP_CLIENT_ID}
                  clientSecret: ${GITHUB_APP_CLIENT_SECRET}
                  webhookUrl: ${GITHUB_APP_WEBHOOK_URL}
                  webhookSecret: ${GITHUB_APP_WEBHOOK_SECRET}
                  privateKey: |
                    ${GITHUB_APP_PRIVATE_KEY}
        enabled:
          github: ${GITHUB_ENABLED}
    ```
    </details>

5. Create a Secret to populate the environmental variables in the ConfigMap
     <details><summary>Secrets Resource</summary>
     
     ```yaml
    kind: Secret
    apiVersion: v1
    metadata:
      name: showcase-secrets
    data:
      GITHUB_ENABLED: dHJ1ZQ==
      GITHUB_APP_PRIVATE_KEY: base64 encoded private key
      GITHUB_APP_CLIENT_SECRET: base64 encoded client secret
      GITHUB_APP_WEBHOOK_URL:  base64 encoded webhook url
      GITHUB_APP_WEBHOOK_SECRET: base64 encoded webhook secret
      GITHUB_APP_APP_ID: base64 encoded app id
      GITHUB_APP_CLIENT_ID: base64 encoded client id
    type: Opaque
    ```
    </details>
6. Add the ConfigMap and Secret to the `values.yaml`
    ```yaml
    upstream:
      backstage:
        extraAppConfig:
          - configMapRef: app-config-showcase
            filename: app-config-showcase.yaml
        extraEnvVarsSecrets:
              - showcase-secrets
7. Deploy the instance with `helm upgrade -i janus-idp -n <namespace> janus-idp/backstage -f ./values.yaml`
8. Observe the logs with `kubectl logs $(kubectl get pods | grep backstage | awk '{print $1}')`
9. See the exposed Private Key

### Versions of software used and environment
- Image used: https://quay.io/repository/janus-idp/backstage-showcase?tab=tags&tag=next-ff2e29c (will expire within 13 days of making this issue)
- [Janus Helm Chart v2.8.1](https://github.com/janus-idp/helm-backstage/tree/31cb6863b793da7893b46420e2beb2f90a5426fe)
- [openshift 4.13.0-0.nightly-2023-11-02-043341](https://amd64.ocp.releases.ci.openshift.org/releasetag/4.13.0-0.nightly-2023-11-02-043341)
- Azure Kubernetes Service (AKS) running Kubernetes v1.26.6
