### ISSUE TITLE
bad ux: Plugin-in needs to be enabled in three places

### ISSUE THREAD

**Issue by kadel** [janus-idp/backstage-showcase#715]
### What do you want to improve?

Currently If I want to enable plugin I have to change it in 
app-config.yaml for example `enabled.githubOrg: true` and then I have to also enable it in `dynamic-plugins.default.yaml`, there it looks like we have also two options to enable/disable plugin
```
    disabled: false
    pluginConfig:
      enabled:
        githubOrg: true
````
