### ISSUE TITLE
Multiple Auth Providers can be registered simultaneously

### ISSUE THREAD

**Issue by Zaperex** [janus-idp/backstage-showcase#788]
### Describe the bug
Currently, the conditional sign-in page renders the sign-in page for the auth provider in the `signInPage` field of the app configurations. 

However, if the user has more than one auth provider configured, and then are able to successfully authenticate with the auth provider in the `signInPage`, they'll then be able to attempt to sign in with the auth providers in the settings menu authentication providers tab since all the auth providers in the configurations are registered regardless of the `signInPage` configurations.
![Auth Provider Tab with a bunch of auth providers](https://github.com/janus-idp/backstage-showcase/assets/50030060/dc831f31-8038-468d-bfac-14b142462306)

### Expected Behavior
Only the auth provider in the `signInPage` configuration should be registered to prevent users from authenticating to the other auth providers.
### What are the steps to reproduce this bug?

1. In the app configurations auth field, provide configurations for 2 auth providers (at least one needs to be valid) and put one of them as the `signInPage`
```yaml
auth:
  environment: development
  providers:
    gitlab:
      development:
        clientId: ${GITHUB_CLIENT_ID}
        clientSecret: ${GITHUB_CLIENT_SECRET}
    github:
      development:
        clientId: ${GITLAB_CLIENT_ID}
        clientSecret: ${GITLAB_CLIENT_SECRET}
signInPage: github
```
2. Sign in to the configured auth provider (in the example above, github is used)
3. Navigate to the Settings -> Authentication Providers
4. Observe that the gitlab auth provider is also registered
