### ISSUE TITLE
Error installing backstage-plugin-catalog-backend-module-github-org-dynamic

### ISSUE THREAD

**Issue by gashcrumb** [janus-idp/backstage-showcase#789]
### Describe the bug

The plugin backstage-plugin-catalog-backend-module-github-org-dynamic is missing an integrity hash

### Expected Behavior

The plugin installs without an error

### What are the steps to reproduce this bug?

1. Configure the helm chart to enable this plugin:

```
global:
  dynamic:
    includes:
      - dynamic-plugins.default.yaml
    plugins:
      - disabled: false
        package: >-
          ./dynamic-plugins/dist/backstage-plugin-catalog-backend-module-github-org-dynamic
```

The developer hub pod won't start, looking at the init container logs theres:

![Screenshot from 2023-11-16 07-46-54](https://github.com/janus-idp/backstage-showcase/assets/351660/6f411a9f-a806-4e5d-bd11-0405a88d46d1)

### Versions of software used and environment
OCP 4.14.1 on openshift local,
Build: 1.0-162
