### ISSUE TITLE
Gitlab Auth provider does not work with private gitlab instances in private networks

### ISSUE THREAD

**Issue by Zaperex** [janus-idp/backstage-showcase#796]
### Describe the bug

When following the [backstage docs](https://backstage.io/docs/auth/gitlab/provider) for configuring the gitlab auth provider, if you set up an application on a private gitlab instance (tested with <https://gitlab.cee.redhat.com>), you won't be able to authenticate as it fails to obtain the access token.

Configurations:
```yaml
auth:
  environment: production
  providers:
    gitlab:
      production:   
        clientId: ${GITLAB_APP_ID}
        clientSecret: ${GITLAB_APP_SECRET}
        audience: https://gitlab.cee.redhat.com
signInPage: gitlab
```

[Screencast from 2023-11-20 10-08-43.webm](https://github.com/janus-idp/backstage-showcase/assets/50030060/b2743728-c173-4935-8742-5b5e26f6caa3)

### Expected Behavior
The gitlab auth provider should be able to retrieve token, and allow the user to login
### What are the steps to reproduce this bug?

1. Setup gitlab app according to [backstage docs](https://backstage.io/docs/auth/gitlab/provider)
2. Configure the gitlab auth provider with the yaml configuration from above
3. Attempt to sign in with gitlab provider (you should have access to the gitlab instance on the machine running backstage)

### Versions of software used and environment
Tested locally with VPN access to the private network
